name = "ExPlanRL"
uuid = "da5ccee6-39e0-4709-8d17-fa5bfab8a1e1"
authors = ["Mateo Llivisaca"]
version = "1.0.0-DEV"

[deps]
ACOPF_Extensions = "f988bfc6-444a-4835-baec-c557783cd6e5"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ACOPF_Extensions = "1"
BSON = "0.3"
Colors = "0.13"
Dates = "1"
Distributed = "1"
Flux = "0.16"
LaTeXStrings = "1"
Plots = "1"
Random = "1"
StatsBase = "0.34"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
